FROM rust:1.54

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    gcc-arm-linux-gnueabihf \
    git \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

RUN rustup target add armv7-unknown-linux-musleabi

ENV CC_armv7_unknown_linux_musleabi arm-linux-gnueabihf-gcc

RUN adduser rust
#USER rust
